title: Onnozone
logo: assets/images/onnozone_logo.png
facebook_pageid: Onnozone-113172183839158
facebook_pagename: Facebook
youtube_channelid: UCIe_v09FFodVGK34RnATljA
youtube_channelname: YouTube
description: >- # this means to ignore newlines until next parameter
  Onnozone is the creative makerspace of Onno Heesbeen Â© 2020
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://onnozone.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_picture_tag
  - jekyll-sitemap

show_excerpts: true
excerpt_separator: <!--more-->
future: true
google_analytics: UA-176126375-1

permalink: pretty

twitter:
  card: summary_large_image

collections:
  category:
    sort_by: order
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

main_ratio: 700:468